### ISSUE TITLE
support for additional fuse mount options in volume mount driver hash

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/nfsv3driver#2]
Thanks for the great work on the NFS support for volume services. We have the following use-case (related to exposing existing NFS shares from existing legacy NFS servers) that doesn't seem yet supported by the driver and which Orange is interested in contributing: 

The ability for NFS brokers to expose some of the [fuse options](http://manpages.ubuntu.com/manpages/precise/man8/mount.fuse.8.html) (such as the caching controls with 
``attr_timeout`` option ``The timeout in seconds for which file/directory attributes are cached.  The default is 1.0 second``) in the volume mount ``device`` section, as to enable tuning of such options without requiring human interactions with the CF operators owning the driver deployment.

Our understanding is that the current ``device`` format supported in NFS driver within the volume mounts is:

```json
"device": {
        "volume_id": "bc2c1eab-05b9-482d-b0cf-750ee07de311",
        "mount_config": {
             "source": "nfs://1.2.3.4:25840/my/share/to/mount?uid=1004&gid=1004"
         }
}
```

To support the use-case above, we considered different alternatives:
1- support additional query parameters options to the ``source`` url
2- add support for other options in the ``mount_config`` entry, independently of the source URL

#2 seems more familiar to current NFS operators: it separate the NFS mount destination from the source URL, so we have a preference for this option. This could result in the following ``device`` value.

```json
"device": {
        "volume_id": "bc2c1eab-05b9-482d-b0cf-750ee07de311",
        "mount_config": {
             "source": "nfs://1.2.3.4:25840/my/share/to/mount?uid=1004&gid=1004",
             "attr_timeout": "0"
        }
}
```

In terms of implementation, we started exploring feasibility in the following proof-of-concepts (which we are currently testing):
- fuse NFS enhancements to add flexibility to supported command-line options, see   https://github.com/orange-cloudfoundry/fuse-nfs/pull/1 that we would submit upstream to sahlberg/fuse-nfs
- cloudfoundry-incubator/nfsbroker [enhancements](https://github.com/orange-cloudfoundry/nfsbroker/blob/add_NFS_options/nfsbroker/nfsbroker.go#L277-L308) to support additional arbitrary params and map them as entries in the volume ``mount_config`` hash. This aims at supporting the existing persistence test pipelines. Orange is instead planning on using a generic broker for all static resources, see  https://github.com/orange-cloudfoundry/static-creds-broker/issues/31
- cloudfoundry-incubator/nfsv3driver [enhancements](https://github.com/orange-cloudfoundry/nfsv3driver/blob/add_NFS_options/nfs_v3_mounter.go#L32-L45) to propagate options specified in the volume mount ``mount_config`` keys as the nfs-fuse command-line arguments

We'd be interested in hearing the persistent team's views on this use-case, along with feedback on the proposed design and implementation. As much as possible, we strive to avoid breaking changes. Also, we would like guidance in the test coverage that would bestenable quick merge of this contribution. We started efforts to try run part of the persistent team CI in our environment, as to validate contributed changes won't break the existing tests. We might need some support in this area.

Thanks in advance for your help,

Nicolas (@nabbar), Stephane (@smaillan) and Guillaume (@gberche-orange).

**Comment by julian-hj** [comment]
Hi Nicolas, Stephane and Guillaume,

Thanks for offering to contribute this feature set!  We agree that it's an important missing feature, and we are looking forward to your pull request.  The proposed design sounds correct, and is more or less how we arrange the plumbing for other options.

**One suggestion**: we found with our other nfs based driver that some mount options are not very safe and can compromise the integrity of the diego cell.  For example, hard mounting remote filesystems without interrupts enabled can result in hung processes.  The options are a little different when fuse mounting, but my guess is that there are some similarly bad options (e.g. r/w file mounts with long timeouts, enabling interrupts on file systems that don't support it, block device mounts, etc.).  To make it safer, I'd suggest to whitelist a set of options that can be set, and default that list to just the ones you need.  You can add a bosh property to allow override of the whitelisted properties, but the general idea is to force the bosh operator to think a little about what properties make sense.

In terms of testing, if you can add unit tests for all of your changes to nfsbroker and nfsv3driver following the patterns we already have in our code, we can do the driver certification tests and end-to-end acceptance tests when we pull in your pull request.  Ordinarily, we would suggest to pairs code with someone in your organization for this final step, but the 9 hour time difference makes this a challenge, unless any of you is planning to travel to the US sometime soon?

Finally, on a more general note, we'd love to hear more from you about how you will use shared volumes in cloud foundry.  Do you have time for a 1 hour meeting some time to walk us through your use cases?  Hearing directly from customers and partners really helps us to prioritize our feature backlog.

**Comment by gberche-orange** [comment]
thanks a lot @julian-hj for your prompt and detailed feedback. We're happy to hear that this use-case seems of value.

We fully agree with your suggestion of an operator-configureable white list of options to be supported in the driver, likely to control both source url args and side options. 

Also, we were wondering how to provide service provider feedback when a non-white-listed option gets returned in the volume mounts:
1- the driver applies a fail-fast approach and rejects non-white listed options, triggering failure of the volume mount, hopefully propagating an error message back to the application developer that requested the corresponding service instance bound to his application, such as "The volume mount failed because the NFS driver is configured to reject the parameter: attr_timeout."
2- the drivers ignores non-white listed options, and issue a log entry only visible to CF operators.
3- The volume mount supports a special option "sloppy_mount" interpreted by the nfsdriver when receiving a non-white listed option. When this option is ommited or set to false, then behavior 1) is applied. Otherwise behavior 2) is applied. This is similar to the [sloppy mount](http://unix.stackexchange.com/questions/174292/linux-sloppy-mount) options usually exposed in mount command as [-s](https://linux.die.net/man/8/mount.nfs) option

We had a preference for option 3), but we have not yet tested error message propagating to application developers. We're happy to hear feedback, including on option naming.

In terms of naming of the bosh nfsdriver job spec file, we were considering:

```
  nfsv3driver.mount-options:
    description: "Comma separated list of white listed options supported. "
    default: "nfs-service-guid"
    example: allow_root, allow_other, nfs_uid, nfs_gid, auto_cache
```

Any suggestion/preference on the nfsdriver configuration format to use (since nfsv3driver does not yet have such config file), along with sample preferred golang styling to read the config ?

> Ordinarily, we would suggest to pairs code with someone in your organization for this final step, but the 9 hour time difference makes this a challenge, unless any of you is planning to travel to the US sometime soon?

Nothing yet planned for short term (although we're looking forward to meeting in person during the CF summit office hours in june). If this make sense, we may be able to pair during 2-3 hours slots alternating mornings and evenings depending on constraints of both sides.

> Finally, on a more general note, we'd love to hear more from you about how you will use shared volumes in cloud foundry.

That'd be great for us too. We don't yet have a full picture yet as we are still in the gradual process of onboarding more production workload: we strive to balance 1) governance of moving towards cloud-native applications with 2) pragmatic support for some legacy apps when we need it. We are now concentrating on statically created NFS share mounts for the next 2-3 mounts, and will expand to other driver backend with on-demand allocation. However, here is a list of available time slots in our agenda for a 1st exchange:
- Mon 30/1 8-9am PST (5-6pm CET Paris time)
- Mon 30/1 9-10am PST (6-7pm CET Paris time)
- Thu 2/2 8-9am PST (5-6pm CET Paris time)
- Thu 2/2 9-10am PST (5-6pm CET Paris time)
- Tues 7/2 8-9am PST (5-6pm CET Paris time)
- Tues 7/2 9-10am PST (6-7pm CET Paris time)
- Mon 13/2 8-9am PST (5-6pm CET Paris time)
- Mon 13/2 9-10am PST (6-7pm CET Paris time)

Thanks again,

Nicolas, Stephane and Guillaume

**Comment by paulcwarren** [comment]
Hi Folks,
We were thinking "broker", rather than driver.  

i.e. any create (or bind) service operation including one or more options that are not in the whitelist would fail that operation immediately (with an appropriate error message back to the user).  Therefore no volume_mount instructions would ever be issued and drivers wouldn't need to handle these situations.

I guess this is most like your option #1, just handled by the broker - not the driver.

**Comment by gberche-orange** [comment]
Thanks @paulcwarren for your feedback.

> We were thinking "broker" whitelist, rather than driver whitelist 

> It seems like you might have a use case that requires the drivers to be involved though, or would this approach work for you?

The rationale for a white-list at the driver level is to provide ways for a CF operator to protect the diego cells against undesired volume mount options that could have different undesired side effects:
- diego cell performance or stability impacts
- possibly security impacts by exploiting zero days vulnerabilities in the fuse NFS implementation that trigger on specific volume options.

 I understand that there are some scenarios (*) in which the cf operator will not have fine control over the broker, and would prefer to ensure at the driver level that all possible volume mounts requests by any registered broker in a CF instance meet a white list of options the diego operator is confident in to offer to both broker authors and developpers using such brokers.

(*) Examples of such scenarios cf operator will not have fine control over the broker
- [user-managed service brokers](https://docs.google.com/document/d/1azArNcDtOjiq5wHx0BCS3OABfJf1PufPmc0OqfkFq7c/edit?usp=sharing) that are [private to one space](http://cli.cloudfoundry.org/en-US/cf/create-service-broker.html))
- a public CF instance which may leverage a public marketplace (e.g. through appdirect or the upcoming open service broker API), and accept to have 3rd parties provide on-demand NFS shares service, through providing their own service broker implementations.

> simpler rather than complicated
> ... and our drivers wouldn't need to be made to handle these where unsupported mount options 

Yes, we do share the same objective of having a simple solution while not sacrifying extensibility.

However, I believe there is value in supporting the following actors and their respective use-cases:
* CF/diego operator:
   * UC1: As a diego operator, in order to guarantee security and SLA of the platform, I need to be able to restrict volume mount options accepted by the drivers I operate, and be able to audit/archive the executed mount options requested to my drivers.
 * NFS service provider:
   * UC2: As an NFS service provider offering remote NFS volume mounts in a marketplace, in order to fine tune the service offered to consummers, I need some way to discover the supported mount options, and ideally some feedback/fallback when a useful mount option isn't supported by platform.
* NFS service consumers:
   * UC3: As an application developer trying out a volume service to fit an application use-case, I just want to be able to use basic remote storage as fast as possible (``I do not care how` (Tm)`) and prefer to have fine tuning details handled later on.
   * UC4: As an application operator consuming a volume service available in the marketplace, I would like my app to have the best performance in production, and therefore most of the fine tuned mount options recommended by the NFF service provider to be taken into account. If some of the recommended mount options is not supported by the CF platform (which may be onprem or public), I would like to be informed so I can offer to mediate between the CF operator and the NFS service provider, or pick alternatives in either CF platform provider or NFS service provider.

Therefore, it might make sense to support a white-list in both nfsdriver and nfsbroker.

For the broker white list, the option 1) or directly returning an error when receiving a non-white listed mount option makes sense.

For the driver white list, I feel the option 3) with the sloppy mount option makes sense to support the above use cases.

To support either UC3 or UC4, the floppy_mount would be accepted in the volume mount such as in the following example, when UC3 a developer asks for ignoring unsupported mount options "it should work, I don't care how", using the nfs broker with service instance proper arbitrary params, (or a custom service broker such as https://github.com/orange-cloudfoundry/static-creds-broker/issues/31), then this results in the following volume_mount broker response, and eventually be processed by the nfsdriver:

```
"device": {
        "volume_id": "bc2c1eab-05b9-482d-b0cf-750ee07de311",
        "mount_config": {
             "source": "nfs://1.2.3.4:25840/my/share/to/mount?uid=1004&gid=1004",
             "attr_timeout": "0",
             "floppy_mount: true"
        }
}
```

or instead UC4, where the operator would want a fail fast, the following volume_mount would eventually reach the nfsdriver:


```
"device": {
        "volume_id": "bc2c1eab-05b9-482d-b0cf-750ee07de311",
        "mount_config": {
             "source": "nfs://1.2.3.4:25840/my/share/to/mount?uid=1004&gid=1004",
             "attr_timeout": "0",
             "floppy_mount: false"
        }
}
```

This could result in the following spec files additions:

for driver:
```
nfsv3driver.source_params:
    description: "Comma separated list of white-listed options that may be configured in supported in the mount_config.source URL query params, formatted as 'option:default'. If an option is not specified in the volume mount, then the specified default value will be used instead."
    example: uid:1000, gid:1000
    default: uid:1000, gid:1000

nfsv3driver.mount_options:
    description: "Comma separated list of white-listed options that may be configured in the mount_config options, formatted as 'option:default'. If an option is not specified in the volume mount, then the specified default value will be used instead. A specific floppy_mount option tells the driver to ignore unsupported options when set to true, or to fail fast instead when receiving an unsupported option when set to false"
    example: allow_root:false, allow_other:false, nfs_uid:2000, nfs_gid:2000, auto_cache:true, floppy_mount:true
    default: auto_cache:true
```

for broker:
```
nfsbroker.source_params:
    description: "Comma separated list of white-listed options that may be configured in supported in the mount_config.source URL query params, formatted as 'option:default'. If an option is not specified in the volume mount, then the specified default value will be used instead. If a non-white-listed option is received from a user as arbitrary params, then the broker will reject the user request. "
    example: uid:1000, gid:1000
    default: uid:1000, gid:1000

nfsbroker.mount_options:
    description: "Comma separated list of white-listed options that may be configured in the mount_config options, formatted as 'option:default'. If an option is not specified in the volume mount, then the specified default value will be used instead. If a non-white-listed option is received from a user as arbitrary params, then the broker will reject the user request. A specific floppy_mount option tells the driver to ignore unsupported options when set to true, or to fail fast instead when receiving an unsupported option when set to false."
    example: allow_root:false, allow_other:false, nfs_uid:2000, nfs_gid:2000, auto_cache:false
    default: auto_cache:true
```

**Comment by julian-hj** [comment]
Hi Folks,

This all makes perfect sense.  I agree that for security/enforcement reasons, adding checks to the broker is not a good substitute to putting them in the driver, because brokers can be deployed by anyone whereas drivers can only be deployed by the operator.  

Unfortunately, however, we don't have a good pathway through Diego and Cloud Foundry to report detailed error messages back to the user that have occurred in the driver during application startup.  Most of the detailed errors end up in the driver logs, which are only accessible to the operator.  So your proposal to put checks in both the broker and the driver seems like the only way to achieve both security and usability.

A couple minor points:
1) in your example above, you include both keys and values for acceptable options.  In some cases, that maybe makes sense, but in others it definitely does not.  So I would expect the source params to look more like: 

```
nfsbroker.source_params:
    description: "Comma separated list of white-listed options that may be configured in supported in the mount_config.source URL query params, formatted as 'option:default' or 'option:' (when no default is specified). If an option is not specified in the volume mount, and a default is available, then the specified default value will be used instead. If a non-white-listed option is received from a user as arbitrary params, then the broker will reject the user request. "
    example: "uid,gid"
    default: "uid,gid"
```

I guess I am wondering in general whether it would not be better to just whitelist the keys that are allowed, and leave the values out of the picture.  For example, if the only allowable value for `allow_root` is "false" why not just disallow setting of `allow_root`?

2) I see that you refer to `sloppy_mount` and `floppy_mount` in different places.  Please use `sloppy_mount`.  `floppy_mount` brings back bad memories of floppy disks for old guys like me.

Regarding a time to meet, probably it is too late to meet this week, so I think this time slot is still good for us if you are available then:

| Tues 7/2 8-9am PST (5-6pm CET Paris time)

It that works for you, then we will send connection information via private message on slack.

Thanks much,
-Julian
